server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
    show-sql: true
api:
  url: api.coincap.io/v2/assets
